#include <stdio.h>
#include <stdio.h>
#include <fcntl.h>
#include "ADMPmerp.h"

herb_tab ht[154] = {
{1, "Arfandas", "cF5NW", "stem/a", "2sp", "*2 healing of fractures"},
{1, "Balaak", "hO5S", "stalk/b", "45gp", "will heal the worst shattered breaks"},
{1, "Boneset", "tM4W", "root/ea", "14gp", "*3 healing of fractures"},
{1, "Bursthelas", "tS7", "stalk/b", "110gp", "repairs bones/joints"},
{1, "Edram", "cF6", "moss/i", "31gp", "mends bone"},
{2, "Alambas", "mS3SW", "gras/a", "10gp", "heals 4 sq feet third degree burns"},
{2, "Aloe", "tH4U", "leaf/a", "5bp", "*2 healing of burns/cuts, mild anaesthetic"},
{2, "Culkas", "aZ4", "leaf/a", "35gp", "heals 10 sq feet of burns"},
{2, "Jojojopo", "fM4", "leaf/a", "9sp", "cures frostbite, heals 2-20 from cold"},
{2, "Kelventari", "tT3U", "berry/a", "19gp", "heals 3rd burns, heals d10/scars"},
{3, "Anserke", "hO6", "root/a", "75gp", "stops bleeding, takes 3 rnds"},
{3, "Belan", "hO5", "nut/i", "40gp", "stops bleeding, takes d10 rnds"},
{3, "Goldern Cress", "mF4W", "herb/ea", "4gp", "stops bleeding 1-5, wounds wont reopen"},
{3, "Harfy", "sS6", "resin/a", "150gp", "immediately stops bleeding"},
{3, "Rumareth", "import-E", "mix/b", "", "stops bleeding, drowsiness"},
{3, "Tulaxar", "tH4N", "leaves/b", "75gp", "stops bleeding"},
{4, "Akbutege", "hS6S", "leaf/ea", "5gp", "heals 1-10 "},
{4, "Arksau", "mT4C", "sap/a", "12gp", "heals 2-12, *2 healing of wounds, antiseptic"},
{4, "Arlan", "tT6W", "leaf/a", "13sp", "heals 4-9"},
{4, "Arman'umas", "", "leaf/cr/a", "", "*2 healing, reduces swelling"},
{4, "Darsurion", "cM3U", "leaf/a", "3sp", "heals 1-6"},
{4, "Draaf", "sO2", "leaf/i", "5sp", "heals 1-10"},
{4, "Chamomile", "mS4W", "flower/br", "7gp", "sleep 2-12 hrs, *3 healing"},
{4, "Gariig", "aZ3", "cactus/i", "55gp", "heals 30"},
{4, "Gefnul", "eV5", "lichen/i", "90gp", "heals 100"},
{4, "Harwite", "mD2M", "moss/ap", "1gp", "heals 5-50"},
{4, "Madarch", "mU6NW", "mix/li", "100gp", "warms, heals all cuts/bleeding in 1-2 hrs"},
{4, "Mirenna", "cM3U", "berry/i", "10gp", "heals 10 (can hold in mouth)"},
{4, "Reglen", "tU4", "moss/b", "75gp", "heals 50, calms"},
{4, "Rewk", "tD3", "nodule/b", "9sp", "heals 2-20"},
{4, "Thurl", "tD1", "clove/b", "1sp", "heals 1-4"},
{4, "Winclamit", "cC7N", "fruit/i", "100gp", "heals 3-300"},
{4, "Yavethalion", "mO5", "fruit/i", "45gp", "heals 5-50"},
{5, "Arlian's Slipper","cM7U", "root/b", "1bp", "+20RR vs. colds, undead:-40 vs morale"},
{5, "Arthond", "cM2", "root/i", "5bp", "+20RR vs colds, *5 healing of respiratory"},
{5, "Arunya", "mS3U", "root/b", "4sp", "lvl 11, sleep/unconsciousness, addictive"},
{5, "Athelas", "tC5W", "leaf/b", "200gp", "can cure anything in the hands of a king "},
{5, "Attanar", "tF4U", "moss/a", "8gp", "cures fever"},
{5, "Avhail", "mS2M", "fruit/ea", "3bp", "mutes hunger, restores from starvation"},
{5, "Baranie", "tH5N", "leaves/b", "2bp", "reduces nausea by 75%"},
{5, "Blue Pine", "cC2NW", "nut/ea", "1cp", "5 seeds equal to a meal of preserved rations"},
{5, "Bodezlist", "sH3S", "tissue/ea", "4gp", "flower's heart equals one day's water"},
{5, "Bog-land Grass", "mS1W", "fibers/weave", "1bp", "tough fibers, waterproof ropes and baskets"},
{5, "Boskone", "tH8", "powder/i", "78gp", "'Awareness' 10-20 rnds, addictive, withdrawal"},
{5, "Caj", "sH5S", "nodule/b", "10gp", "PP recovered in half time, 5% of death"},
{5, "Carnerem", "tS5", "leaf/a", "40gp", "delays poison effects for 24 hrs"},
{5, "Culan", "sA7S", "mix/b", "50gp", "anti-spasmodic, vs some poisons"},
{5, "Delrean", "cC2NW", "bark/a", "3sp", "repels insects (Lvl 7), smells foul"},
{5, "Din Fuinen", "mD6W", "resin/in", "25gp", "amnesia 1-100 days, not perminant"},
{5, "Dragul", "hD4S", "root/b", "25gp", "aware, +10 to all perceptions"},
{5, "Elendils Spear", "tH4N", "root/b", "8gp", "slows poison by 10, purify water 5 gallons"},
{5, "Eyebright", "tA6W", "flower/b", "3gp", "+10 perception, 50' infravision, 1 hour"},
{5, "Faghiu", "fM9NW", "flower/b", "330gp", "serves or loves giver for 1100 days"},
{5, "Feduilas", "mD5NW", "flower/sm", "11sp", "+20 RR Essence/Mental ATs 1-5 hrs, AG/QU at -10"},
{5, "Felmather", "mO5", "leaf/i", "105gp", "mentally sumons a friend, relieves coma"},
{5, "Flur Rort", "Dunlend", "flower/li", "", "antidote for nerve poisons (12th lvl)"},
{5, "Gloriosa", "mD7W", "lichen/a", "10gp", "glows, if applied to blade will cut rock"},
{5, "Goodwort", "mF6W", "seed/li", "23gp", "bolsters good +10 morale,  confusion & dizzines to evil creatures (-50), d4 hrs"},
{5, "Harlindar", "import", "mix/b", "", "safe childbirth"},
{5, "Haruella", "mD7NW", "mix/d", "250gp", "Pinnath Ceren, undead: +30 RR vs Fear, cold/draining ATs, *2 repelling"},
{5, "Kiseoboba", "sH1S", "berry/ea", "1sp", "desert, no thirst sensations"},
{5, "Latha", "cF4N", "stem/b", "10sp", "+10RR vs disease, cures colds, heals 12"},
{5, "Lemsang", "tU5NW", "mushroom/i", "4gp", "a purple 'fur'; a pound = 1 month rations"},
{5, "Maiana", "herbalist", "mix/b", "", "decongestant, halves effects"},
{5, "Margath", "herbalist", "mix/p", "", "anaesthetic"},
{5, "Melandar", "cF3", "moss/b", "12sp", "+10RR disease d10 days"},
{5, "Menelar", "cC5", "cone/b", "65gp", "cures any non-mental disease"},
{5, "Nethandon", "mM5NW", "any/ea", "1gp", "stomach pump, vs ingested poisons"},
{5, "Rose Tree", "mD7W", "nectar/a", "50gp", "poison antidote, +25 to enchantments"},
{5, "Sailcha", "tS8NW", "flower/wear", "50gp", "+10 morale/RRs, +5 DB, 3-7 days"},
{5, "Silraen", "mS3NW", "powder/b", "35sp", "analgesic(25% pain), drowsiness 4-5 hrs"},
{5, "Teldalion", "tD3NW", "bark/p", "5gp", "reduces inflammation, cures infections"},
{5, "Ul-Naza", "eW7", "leaf/i", "450gp", "poison antidote, 1 day"},
{5, "Ur", "fH3", "nut/i", "3gp", "1 days food"},
{5, "Wight Orchid", "tA8W", "root/ea", "300gp", "mind/soul leave body, 10 mile range. RR every mile, failure 51+ soul is lost."},
{6, "Degiik", "hO5", "leaf/i", "100gp", "lifekeeping, 1 day"},
{6, "Laurelin", "mO9", "leaf/i", "999gp", "lifegiving for elves, 28 days "},
{6, "Lothfelag", "mU9NW", "flower/ea", "1000gp", "heals; preserves living tissue, absolves pain, can even give back a lost life"},
{6, "Oiolosse", "fF8", "clove/i", "600gp", "lifegiving for elves, 7 days"},
{6, "Olvar", "fO6", "flower/i", "200gp", "lifekeeping, 2d10 days"},
{6, "Pargen", "hJ8", "berry/i", "800gp", "lifegiving, 4 days"},
{6, "Pathur", "aH4", "nodule/i", "35gp", "lifekeeping, 1 hr"},
{6, "Tyr-fira", "fA9U", "leaf/i", "1200gp", "lifegiving, 56 days"},
{7, "Arnuminas", "mS2NW", "leaf/a", "6bp", "*2 healing ligament/cartilage/muscule"},
{7, "Arpsusar", "tF5", "stalk/b", "30gp", "mends muscules"},
{7, "Curfalaka", "hD6S", "fruit/ea", "5gp", "heals muscules"},
{7, "Dagmather", "sS5", "spine/b", "28gp", "heals cartilage"},
{7, "Ebur", "mO4", "flower/i", "22gp", "repairs sprains"},
{8, "Belramba", "sC6", "lichen/b", "60gp", "repairs nerves"},
{8, "Gorfon", "cA7", "fruit", "", "sleep for 10-20 hrs, all damage healed"},
{8, "Terbas", "mD3", "leaf/a", "2gp", "*2 healing of nerves"},
{9, "Aldaka", "cM5", "root/b", "102gp", "restores sight"},
{9, "Asp Glands", "mD2C", "glands/ea", "100gp", "organ restorer; madness- passes in an hour"},
{9, "Berterin", "mD3", "moss/b", "19gp", "preservative 1 day"},
{9, "Febfendu", "cF4", "root/b", "90gp", "restores hearing"},
{9, "Gildarion", "import", "mix/p", "", "organ repair, rare"},
{9, "Numemelos", "Gondor", "moss/a", "300gp", "The White Tree, nerve regen, organ repair"},
{9, "Siran", "sS6", "clove/i", "80gp", "restores 1 organ, skin disease"},
{9, "Siriena", "sS5", "grass/a", "70gp", "preservative 1 week"},
{9, "Tarnas", "hJ6", "nodule/b", "220gp", "repairs organs"},
{10, "Atigax", "fH4", "root/b", "40gp", "protects eyes, 9 hrs"},
{10, "Breldiar", "mV4", "flower/i", "25gp", "-30 vs MM/OB, +50 to spells/missile ATs, 1 hr, addicitive"},
{10, "Elbens Basket", "mS4NW", "root/b", "3gp", "heart stimulant, haste 1 rnd"},
{10, "Gylvir", "mO5", "algae/i", "45gp", "breathe underwater, 4 hrs"},
{10, "Hiam Moss", "cC6NW", "fungus/b", "9gp", "stimulant 24 hrs, requires rest"},
{10, "Kathkusa", "fW3", "leaf/i", "50gp", "*2 STR, +10 OB, *2 hits, d10 rnds"},
{10, "Kilmakur", "hS5", "root/b", "65gp", "protects vs flame/heat, d10 hrs"},
{10, "Klagul", "sS3", "bud/b", "27gp", "elf sight, 6 hrs"},
{10, "Megillos", "cM3", "leaf/i", "12sp", "inc's smell/sight, 10 mins"},
{10, "Sha", "cH7NW", "flower/i", "10gp", "15 rnds infravision, 45 days cramps"},
{10, "Yaran", "tS2", "pollen/i", "9sp", "acute smell/taste, 1 hr"},
{10, "Zulsendura", "aU4", "mushroom/i", "70gp", "haste, 3 rnds"},
{10, "Zur", "cU4", "fungus/b", "12gp", "enhances smell/hearing, 1 hr"},
{11, "Lestagii", "aZ9", "bud/i", "520gp", "restores stats losses"},
{11, "Merrig", "sS5", "thorn/b", "2gp", "inc's PR/AP +5, addiction"},
{12, "Lainimit", "hD2S", "leaf/ea", "1gp", "stun relief, 3 rnds"},
{12, "Suranie", "tF3SW", "berry/i", "2gp", "stun relief, 1 rnd (can hold in mouth)"},
{12, "Vinuk", "sS4", "root/i", "4gp", "stun relief, d10 rnds"},
{12, "Welwal", "mF4", "leaf/i", "12gp", "stun relief, 2 rnds, (can hold in mouth)"},
{12, "Witan", "hJ6S", "leaf/i", "12gp", "stun relief, 2 rnds"},
{13, "Acaana", "fM7", "flower/p", "600gp", "lvl 10, instantly"},
{13, "Asp venom", "mT3C", "Asp/p", "23gp", "lvl 5, limb loss"},
{13, "Black Vine", "cC9NW", "leaf/i", "205gp", "lvl 7, euphoria 1-100 hrs"},
{13, "Camadarch", "cU9C", "mushroom/b", "175gp", "lvl 6, blue skin, body rot"},
{13, "Dynallca", "hF3", "leaf/p", "14gp", "lvl 3, hearing, d10 hits"},
{13, "Galenaana", "cA6", "leaf/po", "179gp", "lvl 6, kills elves, coma others"},
{13, "Jegga", "mU5", "bats/p", "92gp", "lvl 7, 1-100 hits"},
{13, "Jitsu", "mO4", "clams/li", "34gp", "lvl 5, 1-50 hits"},
{13, "Juth", "aZ5", "scorpion/li", "41gp", "lvl 2, insanity"},
{13, "Karfar", "hJ4S", "leaf/p", "142gp", "lvl 7, kills 2d6 rnds"},
{13, "Kly", "sH5", "berry/p", "154gp", "lvl 3, 3-300 hits"},
{13, "Klytun", "sB4S", "root/p", "53gp", "lvl 5, d10 day coma"},
{13, "Lawrim", "fM7NW", "lichen/b", "25gp", "lvl 3, pain d10 rnds, paralysis d10 hrs"},
{13, "Lus", "tT3", "flower/p", "31gp", "lvl 4, d12 rnds"},
{13, "Silmaana", "mT2", "stalk/p", "4gp", "lvl 9, 2d10 hits"},
{13, "Slota", "tD7", "spider/p", "36gp", "lvl 5, paralysis & death"},
{13, "Taynaga", "cC5", "bark/po", "27gp", "lvl 8, 5-50 hits, sterilizies"},
{13, "Uraana", "tS3", "leaf/p", "12gp", "lvl 6, 3-30 hits"},
{13, "Zaganzar", "tM6", "root/li", "139gp", "lvl 2, blinds, d10 hits"},
{13, "Worlclivur", "tO5", "lichen/a", "", "lvl 4, effects eyes"},
{14, "Ancalthur", "tF", "stem/li/a", "", "time sense warped for 2-4 hrs (-50+)"},
{14, "Brorkwilb", "mV4", "flower/i", "9gp", "euphoric, shared family dreams, V addictive"},
{14, "Chrume", "tU4", "mushroom/i", "15sp", "euphoric stimulant, easily distracted"},
{14, "Ecsasse", "mH6", "clove/b", "20gp", "stimulant/hallucinogen, friendly, mind ATs"},
{14, "Feduilas", "tH6NW", "flower/sm", "11sp", "relaxant, +20RR vs Essence 1-5 hrs, AG -10"},
{14, "Gort", "mF5", "leaves/in", "10gp", "hallucinogen, +10 PR 2 hrs, -50 d10 hrs"},
{14, "Hoak-foer", "sS3", "flower/i", "67gp", "hallucinogen, cures mind loss/diseases but prevents movement for d10 weeks"},
{14, "Kirtir", "mT5NW", "buds/ea", "5gp", "stimulant, AG +10 1 hr, CON -30 d10 hrs"},
{14, "Lu Jy Mirenna", "fA7", "berry/i", "100gp", "powerful hallucinogen, visions - beneficial, frequent use perilous"},
{14, "Nelisse", "sV5", "leaf/b", "9sp", "euphoria (-50) for 1 hr, 1 days food"},
{14, "Pipeweed", "mS3U", "leaf/sm", "4sp", "addictive. relaxant -10 for 1-2 hrs"},
{14, "Tartiella", "tF4NW", "weed/sm", "4sp", "relaxant, all stats -10 d10 hrs, happy"},
{14, "Temsanc", "Arnor", "mushroom/li", "", "increases effects of alcohol, common"},
{0, "", "", "", "", ""}};

/*****************************************************************************/
main()
{
int file;
int i,j,sz;
char *rdata;

  if ((file = open("tab_xh.dat", O_BINARY|O_TRUNC|O_RDWR|O_CREAT)) != -1)
  {
	write(file, &ht[0].herb_type, sizeof(ht));
	close(file);
  }
}
