#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include "ADMPmerp.h"

players party[32];

main()
{
int file, x=0, i=-1,j ,sz;
char *rdata;


  memset(&party[0].Name[0], '\0', sizeof(players)*31);

  strcpy(&party[x++].Name[0], "Bandit - 3");
  strcpy(&party[x++].Name[0], "Bandit Ldr - 6");
  strcpy(&party[x++].Name[0], "Bear, Cave");
  strcpy(&party[x++].Name[0], "Cave Worm");
  strcpy(&party[x++].Name[0], "Fighter - 6");
  strcpy(&party[x++].Name[0], "Ghost, Gtr");
  strcpy(&party[x++].Name[0], "Ghoul");
  strcpy(&party[x++].Name[0], "Giant, Lsr");
  strcpy(&party[x++].Name[0], "Kraken, Med");
  strcpy(&party[x++].Name[0], "Mage - 6");
  strcpy(&party[x++].Name[0], "Orc - 7");
  strcpy(&party[x++].Name[0], "Skeleton, Lord ");
  strcpy(&party[x++].Name[0], "Skeleton, Gtr");
  strcpy(&party[x++].Name[0], "Troll, Cave");
  strcpy(&party[x++].Name[0], "Troll, Forest");
  strcpy(&party[x++].Name[0], "Troll, Stone");
  strcpy(&party[x++].Name[0], "Urak Hai");
  strcpy(&party[x++].Name[0], "Warg - 5");
  strcpy(&party[x++].Name[0], "Warg - 8");
  strcpy(&party[x++].Name[0], "Wight, Lesser");
  strcpy(&party[x++].Name[0], "Wolf - 6");
  for (x=21; x<32; x++) {
	  sprintf(&party[x].Name[0], "Monster - %d", x);
  }

strcpy(party[++i].Name, "Bandit - 5"); 
party[i].Level = 5; 
party[i].HitsMax = 66; 
party[i].HitsCur = 66; 
party[i].NoAttks = 1; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 25; 
party[i].SpellBase = 0; 
party[i].DBShield = 25; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 10; 
party[i].AGQU = 90; 
party[i].Armor = 1; 
party[i].CON = 90; 
party[i].Size = 1; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 0; 
party[i].CritAdj = 0; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "BroadSword"); 
strcpy(party[i].weap[0].wp_tbl, "1E"); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 70; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 4; 
party[i].weap[0].wp_fm = 3; 
party[i].weap[0].wp_br = 0; 
party[i].weap[0].wp_bf = 160; 
party[i].weap[0].wp_str = 75; 
strcpy(party[i].weap[0].wp_pc, "S"); 
strcpy(party[i].weap[0].wp_sc, ""); 
strcpy(party[i].weap[0].wp_sm, ""); 
strcpy(party[i].weap[1].wp_dsc, "Melee"); 
strcpy(party[i].weap[1].wp_tbl, ""); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 0; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 0; 
party[i].weap[1].wp_fm = 0; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, ""); 
strcpy(party[i].weap[1].wp_sc, ""); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Short Bow"); 
strcpy(party[i].weap[3].wp_tbl, "MS"); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 60; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 2; 
party[i].weap[3].wp_fm = 4; 
party[i].weap[3].wp_br = 60; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, "P"); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, ""); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 0; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 0; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, ""); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Bandit Ldr - 6"); 
party[i].Level = 6; 
party[i].HitsMax = 85; 
party[i].HitsCur = 85; 
party[i].NoAttks = 1; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 30; 
party[i].SpellBase = 0; 
party[i].DBShield = 25; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 10; 
party[i].AGQU = 90; 
party[i].Armor = 2; 
party[i].CON = 90; 
party[i].Size = 1; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 0; 
party[i].CritAdj = 0; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "BroadSword"); 
strcpy(party[i].weap[0].wp_tbl, "1E"); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 80; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 4; 
party[i].weap[0].wp_fm = 3; 
party[i].weap[0].wp_br = 0; 
party[i].weap[0].wp_bf = 160; 
party[i].weap[0].wp_str = 75; 
strcpy(party[i].weap[0].wp_pc, "S"); 
strcpy(party[i].weap[0].wp_sc, ""); 
strcpy(party[i].weap[0].wp_sm, ""); 
strcpy(party[i].weap[1].wp_dsc, "Melee"); 
strcpy(party[i].weap[1].wp_tbl, ""); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 0; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 0; 
party[i].weap[1].wp_fm = 0; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, ""); 
strcpy(party[i].weap[1].wp_sc, ""); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Short Bow"); 
strcpy(party[i].weap[3].wp_tbl, "MS"); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 70; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 2; 
party[i].weap[3].wp_fm = 4; 
party[i].weap[3].wp_br = 60; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, "P"); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, ""); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 0; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 0; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, ""); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Bear, Cave"); 
party[i].Level = 12; 
party[i].HitsMax = 266; 
party[i].HitsCur = 266; 
party[i].NoAttks = 2; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 40; 
party[i].SpellBase = 0; 
party[i].DBShield = 0; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 30; 
party[i].AGQU = 100; 
party[i].Armor = 2; 
party[i].CON = 90; 
party[i].Size = 1; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 0; 
party[i].CritAdj = 0; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "Claw"); 
strcpy(party[i].weap[0].wp_tbl, "TC"); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 90; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 5; 
party[i].weap[0].wp_fm = 2; 
party[i].weap[0].wp_br = 0; 
party[i].weap[0].wp_bf = 0; 
party[i].weap[0].wp_str = 0; 
strcpy(party[i].weap[0].wp_pc, "S"); 
strcpy(party[i].weap[0].wp_sc, "pb"); 
strcpy(party[i].weap[0].wp_sm, ""); 
strcpy(party[i].weap[1].wp_dsc, "Claw"); 
strcpy(party[i].weap[1].wp_tbl, "TC"); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 90; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 5; 
party[i].weap[1].wp_fm = 2; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, "S"); 
strcpy(party[i].weap[1].wp_sc, "pb"); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Missile"); 
strcpy(party[i].weap[3].wp_tbl, ""); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 0; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 0; 
party[i].weap[3].wp_fm = 0; 
party[i].weap[3].wp_br = 0; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, ""); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, ""); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 0; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 0; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, ""); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Cave Worm"); 
party[i].Level = 0; 
party[i].HitsMax = 66; 
party[i].HitsCur = 66; 
party[i].NoAttks = 1; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 0; 
party[i].SpellBase = 0; 
party[i].DBShield = 0; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 0; 
party[i].AGQU = 0; 
party[i].Armor = 0; 
party[i].CON = 90; 
party[i].Size = 1; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 0; 
party[i].CritAdj = 0; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "Melee"); 
strcpy(party[i].weap[0].wp_tbl, ""); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 0; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 0; 
party[i].weap[0].wp_fm = 0; 
party[i].weap[0].wp_br = 0; 
party[i].weap[0].wp_bf = 0; 
party[i].weap[0].wp_str = 0; 
strcpy(party[i].weap[0].wp_pc, ""); 
strcpy(party[i].weap[0].wp_sc, ""); 
strcpy(party[i].weap[0].wp_sm, ""); 
strcpy(party[i].weap[1].wp_dsc, "Melee"); 
strcpy(party[i].weap[1].wp_tbl, ""); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 0; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 0; 
party[i].weap[1].wp_fm = 0; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, ""); 
strcpy(party[i].weap[1].wp_sc, ""); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Missile"); 
strcpy(party[i].weap[3].wp_tbl, ""); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 0; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 0; 
party[i].weap[3].wp_fm = 0; 
party[i].weap[3].wp_br = 0; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, ""); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, ""); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 0; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 0; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, ""); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Fighter - 6"); 
party[i].Level = 6; 
party[i].HitsMax = 111; 
party[i].HitsCur = 111; 
party[i].NoAttks = 1; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 30; 
party[i].SpellBase = 0; 
party[i].DBShield = 30; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 30; 
party[i].AGQU = 100; 
party[i].Armor = 3; 
party[i].CON = 90; 
party[i].Size = 1; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 0; 
party[i].CritAdj = 0; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "BroadSword"); 
strcpy(party[i].weap[0].wp_tbl, "1E"); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 89; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 4; 
party[i].weap[0].wp_fm = 3; 
party[i].weap[0].wp_br = 0; 
party[i].weap[0].wp_bf = 160; 
party[i].weap[0].wp_str = 75; 
strcpy(party[i].weap[0].wp_pc, "S"); 
strcpy(party[i].weap[0].wp_sc, ""); 
strcpy(party[i].weap[0].wp_sm, ""); 
strcpy(party[i].weap[1].wp_dsc, "Melee"); 
strcpy(party[i].weap[1].wp_tbl, ""); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 0; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 0; 
party[i].weap[1].wp_fm = 0; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, ""); 
strcpy(party[i].weap[1].wp_sc, ""); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Short Bow"); 
strcpy(party[i].weap[3].wp_tbl, "MS"); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 71; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 2; 
party[i].weap[3].wp_fm = 4; 
party[i].weap[3].wp_br = 60; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, "P"); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, ""); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 0; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 0; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, ""); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Ghost, Gtr"); 
party[i].Level = 15; 
party[i].HitsMax = 160; 
party[i].HitsCur = 160; 
party[i].NoAttks = 1; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 50; 
party[i].SpellBase = 0; 
party[i].DBShield = 0; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 20; 
party[i].AGQU = 90; 
party[i].Armor = 0; 
party[i].CON = 90; 
party[i].Size = 1; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 3; 
party[i].CritAdj = 3; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "BroadSword"); 
strcpy(party[i].weap[0].wp_tbl, "1E"); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 110; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 4; 
party[i].weap[0].wp_fm = 3; 
party[i].weap[0].wp_br = 0; 
party[i].weap[0].wp_bf = 160; 
party[i].weap[0].wp_str = 75; 
strcpy(party[i].weap[0].wp_pc, "S"); 
strcpy(party[i].weap[0].wp_sc, ""); 
strcpy(party[i].weap[0].wp_sm, ""); 
strcpy(party[i].weap[1].wp_dsc, "Melee"); 
strcpy(party[i].weap[1].wp_tbl, ""); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 0; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 0; 
party[i].weap[1].wp_fm = 0; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, ""); 
strcpy(party[i].weap[1].wp_sc, ""); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Missile"); 
strcpy(party[i].weap[3].wp_tbl, ""); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 0; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 0; 
party[i].weap[3].wp_fm = 0; 
party[i].weap[3].wp_br = 0; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, ""); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, ""); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 0; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 0; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, ""); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Ghoul"); 
party[i].Level = 0; 
party[i].HitsMax = 66; 
party[i].HitsCur = 66; 
party[i].NoAttks = 1; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 0; 
party[i].SpellBase = 0; 
party[i].DBShield = 0; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 0; 
party[i].AGQU = 0; 
party[i].Armor = 0; 
party[i].CON = 90; 
party[i].Size = 1; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 0; 
party[i].CritAdj = 0; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "Melee"); 
strcpy(party[i].weap[0].wp_tbl, ""); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 0; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 0; 
party[i].weap[0].wp_fm = 0; 
party[i].weap[0].wp_br = 0; 
party[i].weap[0].wp_bf = 0; 
party[i].weap[0].wp_str = 0; 
strcpy(party[i].weap[0].wp_pc, ""); 
strcpy(party[i].weap[0].wp_sc, ""); 
strcpy(party[i].weap[0].wp_sm, ""); 
strcpy(party[i].weap[1].wp_dsc, "Melee"); 
strcpy(party[i].weap[1].wp_tbl, ""); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 0; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 0; 
party[i].weap[1].wp_fm = 0; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, ""); 
strcpy(party[i].weap[1].wp_sc, ""); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Missile"); 
strcpy(party[i].weap[3].wp_tbl, ""); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 0; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 0; 
party[i].weap[3].wp_fm = 0; 
party[i].weap[3].wp_br = 0; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, ""); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, ""); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 0; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 0; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, ""); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Giant, Lsr"); 
party[i].Level = 0; 
party[i].HitsMax = 66; 
party[i].HitsCur = 66; 
party[i].NoAttks = 1; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 0; 
party[i].SpellBase = 0; 
party[i].DBShield = 0; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 0; 
party[i].AGQU = 0; 
party[i].Armor = 0; 
party[i].CON = 90; 
party[i].Size = 1; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 0; 
party[i].CritAdj = 0; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "Melee"); 
strcpy(party[i].weap[0].wp_tbl, ""); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 0; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 0; 
party[i].weap[0].wp_fm = 0; 
party[i].weap[0].wp_br = 0; 
party[i].weap[0].wp_bf = 0; 
party[i].weap[0].wp_str = 0; 
strcpy(party[i].weap[0].wp_pc, ""); 
strcpy(party[i].weap[0].wp_sc, ""); 
strcpy(party[i].weap[0].wp_sm, ""); 
strcpy(party[i].weap[1].wp_dsc, "Melee"); 
strcpy(party[i].weap[1].wp_tbl, ""); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 0; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 0; 
party[i].weap[1].wp_fm = 0; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, ""); 
strcpy(party[i].weap[1].wp_sc, ""); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Missile"); 
strcpy(party[i].weap[3].wp_tbl, ""); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 0; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 0; 
party[i].weap[3].wp_fm = 0; 
party[i].weap[3].wp_br = 0; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, ""); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, ""); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 0; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 0; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, ""); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Kraken, Med"); 
party[i].Level = 0; 
party[i].HitsMax = 66; 
party[i].HitsCur = 66; 
party[i].NoAttks = 1; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 0; 
party[i].SpellBase = 0; 
party[i].DBShield = 0; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 0; 
party[i].AGQU = 0; 
party[i].Armor = 0; 
party[i].CON = 90; 
party[i].Size = 1; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 0; 
party[i].CritAdj = 0; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "Melee"); 
strcpy(party[i].weap[0].wp_tbl, ""); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 0; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 0; 
party[i].weap[0].wp_fm = 0; 
party[i].weap[0].wp_br = 0; 
party[i].weap[0].wp_bf = 0; 
party[i].weap[0].wp_str = 0; 
strcpy(party[i].weap[0].wp_pc, ""); 
strcpy(party[i].weap[0].wp_sc, ""); 
strcpy(party[i].weap[0].wp_sm, ""); 
strcpy(party[i].weap[1].wp_dsc, "Melee"); 
strcpy(party[i].weap[1].wp_tbl, ""); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 0; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 0; 
party[i].weap[1].wp_fm = 0; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, ""); 
strcpy(party[i].weap[1].wp_sc, ""); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Missile"); 
strcpy(party[i].weap[3].wp_tbl, ""); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 0; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 0; 
party[i].weap[3].wp_fm = 0; 
party[i].weap[3].wp_br = 0; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, ""); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, ""); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 0; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 0; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, ""); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Mage - 6"); 
party[i].Level = 6; 
party[i].HitsMax = 66; 
party[i].HitsCur = 66; 
party[i].NoAttks = 1; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 15; 
party[i].SpellBase = 12; 
party[i].DBShield = 0; 
party[i].SpellDirAttacks = 73; 
party[i].MMBase = 10; 
party[i].AGQU = 78; 
party[i].Armor = 0; 
party[i].CON = 90; 
party[i].Size = 1; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 0; 
party[i].CritAdj = 0; 
party[i].RRPoison = 15; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 20; 
party[i].RRDisease = 15; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "Dagger"); 
strcpy(party[i].weap[0].wp_tbl, "1E"); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 30; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 1; 
party[i].weap[0].wp_fm = 1; 
party[i].weap[0].wp_br = 15; 
party[i].weap[0].wp_bf = 195; 
party[i].weap[0].wp_str = 18; 
strcpy(party[i].weap[0].wp_pc, "Pc"); 
strcpy(party[i].weap[0].wp_sc, ""); 
strcpy(party[i].weap[0].wp_sm, "CH | PL AK OB-15"); 
strcpy(party[i].weap[1].wp_dsc, "Melee"); 
strcpy(party[i].weap[1].wp_tbl, ""); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 0; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 0; 
party[i].weap[1].wp_fm = 0; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, ""); 
strcpy(party[i].weap[1].wp_sc, ""); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Missile"); 
strcpy(party[i].weap[3].wp_tbl, ""); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 0; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 0; 
party[i].weap[3].wp_fm = 0; 
party[i].weap[3].wp_br = 0; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, ""); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, ""); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 0; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 0; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, ""); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Orc - 7"); 
party[i].Level = 7; 
party[i].HitsMax = 97; 
party[i].HitsCur = 97; 
party[i].NoAttks = 1; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 45; 
party[i].SpellBase = 0; 
party[i].DBShield = 25; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 20; 
party[i].AGQU = 95; 
party[i].Armor = 3; 
party[i].CON = 90; 
party[i].Size = 1; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 0; 
party[i].CritAdj = 0; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "War Hammer"); 
strcpy(party[i].weap[0].wp_tbl, "1C"); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 99; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 5; 
party[i].weap[0].wp_fm = 4; 
party[i].weap[0].wp_br = 10; 
party[i].weap[0].wp_bf = 155; 
party[i].weap[0].wp_str = 60; 
strcpy(party[i].weap[0].wp_pc, "K"); 
strcpy(party[i].weap[0].wp_sc, ""); 
strcpy(party[i].weap[0].wp_sm, "AK OB+5"); 
strcpy(party[i].weap[1].wp_dsc, "Melee"); 
strcpy(party[i].weap[1].wp_tbl, ""); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 0; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 0; 
party[i].weap[1].wp_fm = 0; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, ""); 
strcpy(party[i].weap[1].wp_sc, ""); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Short Bow"); 
strcpy(party[i].weap[3].wp_tbl, "MS"); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 85; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 2; 
party[i].weap[3].wp_fm = 4; 
party[i].weap[3].wp_br = 60; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, "P"); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, ""); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 0; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 0; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, ""); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Skeleton, Lord "); 
party[i].Level = 8; 
party[i].HitsMax = 135; 
party[i].HitsCur = 135; 
party[i].NoAttks = 1; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 50; 
party[i].SpellBase = 0; 
party[i].DBShield = 20; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 20; 
party[i].AGQU = 99; 
party[i].Armor = 3; 
party[i].CON = 90; 
party[i].Size = 1; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 3; 
party[i].CritAdj = 0; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "BroadSword"); 
strcpy(party[i].weap[0].wp_tbl, "1E"); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 115; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 4; 
party[i].weap[0].wp_fm = 3; 
party[i].weap[0].wp_br = 0; 
party[i].weap[0].wp_bf = 160; 
party[i].weap[0].wp_str = 75; 
strcpy(party[i].weap[0].wp_pc, "S"); 
strcpy(party[i].weap[0].wp_sc, ""); 
strcpy(party[i].weap[0].wp_sm, ""); 
strcpy(party[i].weap[1].wp_dsc, "Melee"); 
strcpy(party[i].weap[1].wp_tbl, ""); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 0; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 0; 
party[i].weap[1].wp_fm = 0; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, ""); 
strcpy(party[i].weap[1].wp_sc, ""); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Missile"); 
strcpy(party[i].weap[3].wp_tbl, ""); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 0; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 0; 
party[i].weap[3].wp_fm = 0; 
party[i].weap[3].wp_br = 0; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, ""); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, ""); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 0; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 0; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, ""); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Skeleton, Gtr"); 
party[i].Level = 5; 
party[i].HitsMax = 100; 
party[i].HitsCur = 100; 
party[i].NoAttks = 1; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 55; 
party[i].SpellBase = 0; 
party[i].DBShield = 0; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 20; 
party[i].AGQU = 99; 
party[i].Armor = 2; 
party[i].CON = 90; 
party[i].Size = 1; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 3; 
party[i].CritAdj = 0; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "BroadSword"); 
strcpy(party[i].weap[0].wp_tbl, "1E"); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 95; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 4; 
party[i].weap[0].wp_fm = 3; 
party[i].weap[0].wp_br = 0; 
party[i].weap[0].wp_bf = 160; 
party[i].weap[0].wp_str = 75; 
strcpy(party[i].weap[0].wp_pc, "S"); 
strcpy(party[i].weap[0].wp_sc, ""); 
strcpy(party[i].weap[0].wp_sm, ""); 
strcpy(party[i].weap[1].wp_dsc, "Melee"); 
strcpy(party[i].weap[1].wp_tbl, ""); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 0; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 0; 
party[i].weap[1].wp_fm = 0; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, ""); 
strcpy(party[i].weap[1].wp_sc, ""); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Missile"); 
strcpy(party[i].weap[3].wp_tbl, ""); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 0; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 0; 
party[i].weap[3].wp_fm = 0; 
party[i].weap[3].wp_br = 0; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, ""); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, ""); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 0; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 0; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, ""); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Troll, Cave"); 
party[i].Level = 12; 
party[i].HitsMax = 166; 
party[i].HitsCur = 166; 
party[i].NoAttks = 1; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 30; 
party[i].SpellBase = 0; 
party[i].DBShield = 0; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 15; 
party[i].AGQU = 99; 
party[i].Armor = 2; 
party[i].CON = 90; 
party[i].Size = 2; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 0; 
party[i].CritAdj = 3; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "Club"); 
strcpy(party[i].weap[0].wp_tbl, "1C"); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 106; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 5; 
party[i].weap[0].wp_fm = 4; 
party[i].weap[0].wp_br = 2; 
party[i].weap[0].wp_bf = 140; 
party[i].weap[0].wp_str = 10; 
strcpy(party[i].weap[0].wp_pc, "Kd"); 
strcpy(party[i].weap[0].wp_sc, ""); 
strcpy(party[i].weap[0].wp_sm, "AK OB-10"); 
strcpy(party[i].weap[1].wp_dsc, "Melee"); 
strcpy(party[i].weap[1].wp_tbl, ""); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 0; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 0; 
party[i].weap[1].wp_fm = 0; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, ""); 
strcpy(party[i].weap[1].wp_sc, ""); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Short Bow"); 
strcpy(party[i].weap[3].wp_tbl, "MS"); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 108; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 2; 
party[i].weap[3].wp_fm = 4; 
party[i].weap[3].wp_br = 60; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, "P"); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, "MS"); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 90; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 4; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, "K"); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Troll, Forest"); 
party[i].Level = 8; 
party[i].HitsMax = 100; 
party[i].HitsCur = 100; 
party[i].NoAttks = 1; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 20; 
party[i].SpellBase = 0; 
party[i].DBShield = 0; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 10; 
party[i].AGQU = 90; 
party[i].Armor = 2; 
party[i].CON = 90; 
party[i].Size = 2; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 0; 
party[i].CritAdj = 2; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "Club"); 
strcpy(party[i].weap[0].wp_tbl, "1C"); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 80; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 5; 
party[i].weap[0].wp_fm = 4; 
party[i].weap[0].wp_br = 2; 
party[i].weap[0].wp_bf = 140; 
party[i].weap[0].wp_str = 10; 
strcpy(party[i].weap[0].wp_pc, "Kd"); 
strcpy(party[i].weap[0].wp_sc, ""); 
strcpy(party[i].weap[0].wp_sm, "AK OB-10"); 
strcpy(party[i].weap[1].wp_dsc, "Melee"); 
strcpy(party[i].weap[1].wp_tbl, ""); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 0; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 0; 
party[i].weap[1].wp_fm = 0; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, ""); 
strcpy(party[i].weap[1].wp_sc, ""); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Short Bow"); 
strcpy(party[i].weap[3].wp_tbl, "MS"); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 76; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 2; 
party[i].weap[3].wp_fm = 4; 
party[i].weap[3].wp_br = 60; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, "P"); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, "MS"); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 70; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 4; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, "K"); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Troll, Stone"); 
party[i].Level = 6; 
party[i].HitsMax = 120; 
party[i].HitsCur = 120; 
party[i].NoAttks = 1; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 15; 
party[i].SpellBase = 0; 
party[i].DBShield = 0; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 10; 
party[i].AGQU = 90; 
party[i].Armor = 2; 
party[i].CON = 90; 
party[i].Size = 2; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 0; 
party[i].CritAdj = 2; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "Club"); 
strcpy(party[i].weap[0].wp_tbl, "1C"); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 80; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 5; 
party[i].weap[0].wp_fm = 4; 
party[i].weap[0].wp_br = 2; 
party[i].weap[0].wp_bf = 140; 
party[i].weap[0].wp_str = 10; 
strcpy(party[i].weap[0].wp_pc, "Kd"); 
strcpy(party[i].weap[0].wp_sc, ""); 
strcpy(party[i].weap[0].wp_sm, "AK OB-10"); 
strcpy(party[i].weap[1].wp_dsc, "Melee"); 
strcpy(party[i].weap[1].wp_tbl, ""); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 0; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 0; 
party[i].weap[1].wp_fm = 0; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, ""); 
strcpy(party[i].weap[1].wp_sc, ""); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Short Bow"); 
strcpy(party[i].weap[3].wp_tbl, "MS"); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 82; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 2; 
party[i].weap[3].wp_fm = 4; 
party[i].weap[3].wp_br = 60; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, "P"); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, "MS"); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 65; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 4; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, "K"); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Urak Hai"); 
party[i].Level = 0; 
party[i].HitsMax = 66; 
party[i].HitsCur = 66; 
party[i].NoAttks = 1; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 0; 
party[i].SpellBase = 0; 
party[i].DBShield = 0; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 0; 
party[i].AGQU = 0; 
party[i].Armor = 0; 
party[i].CON = 90; 
party[i].Size = 1; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 0; 
party[i].CritAdj = 0; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "Melee"); 
strcpy(party[i].weap[0].wp_tbl, ""); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 0; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 0; 
party[i].weap[0].wp_fm = 0; 
party[i].weap[0].wp_br = 0; 
party[i].weap[0].wp_bf = 0; 
party[i].weap[0].wp_str = 0; 
strcpy(party[i].weap[0].wp_pc, ""); 
strcpy(party[i].weap[0].wp_sc, ""); 
strcpy(party[i].weap[0].wp_sm, ""); 
strcpy(party[i].weap[1].wp_dsc, "Melee"); 
strcpy(party[i].weap[1].wp_tbl, ""); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 0; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 0; 
party[i].weap[1].wp_fm = 0; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, ""); 
strcpy(party[i].weap[1].wp_sc, ""); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Missile"); 
strcpy(party[i].weap[3].wp_tbl, ""); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 0; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 0; 
party[i].weap[3].wp_fm = 0; 
party[i].weap[3].wp_br = 0; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, ""); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, ""); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 0; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 0; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, ""); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Warg - 5"); 
party[i].Level = 0; 
party[i].HitsMax = 66; 
party[i].HitsCur = 66; 
party[i].NoAttks = 1; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 0; 
party[i].SpellBase = 0; 
party[i].DBShield = 0; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 0; 
party[i].AGQU = 0; 
party[i].Armor = 0; 
party[i].CON = 90; 
party[i].Size = 1; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 0; 
party[i].CritAdj = 0; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "Melee"); 
strcpy(party[i].weap[0].wp_tbl, ""); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 0; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 0; 
party[i].weap[0].wp_fm = 0; 
party[i].weap[0].wp_br = 0; 
party[i].weap[0].wp_bf = 0; 
party[i].weap[0].wp_str = 0; 
strcpy(party[i].weap[0].wp_pc, ""); 
strcpy(party[i].weap[0].wp_sc, ""); 
strcpy(party[i].weap[0].wp_sm, ""); 
strcpy(party[i].weap[1].wp_dsc, "Melee"); 
strcpy(party[i].weap[1].wp_tbl, ""); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 0; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 0; 
party[i].weap[1].wp_fm = 0; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, ""); 
strcpy(party[i].weap[1].wp_sc, ""); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Missile"); 
strcpy(party[i].weap[3].wp_tbl, ""); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 0; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 0; 
party[i].weap[3].wp_fm = 0; 
party[i].weap[3].wp_br = 0; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, ""); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, ""); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 0; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 0; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, ""); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Warg - 8"); 
party[i].Level = 8; 
party[i].HitsMax = 150; 
party[i].HitsCur = 150; 
party[i].NoAttks = 2; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 55; 
party[i].SpellBase = 0; 
party[i].DBShield = 0; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 40; 
party[i].AGQU = 101; 
party[i].Armor = 0; 
party[i].CON = 90; 
party[i].Size = 2; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 3; 
party[i].CritAdj = 1; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "Bite"); 
strcpy(party[i].weap[0].wp_tbl, "TC"); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 90; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 5; 
party[i].weap[0].wp_fm = 2; 
party[i].weap[0].wp_br = 0; 
party[i].weap[0].wp_bf = 0; 
party[i].weap[0].wp_str = 0; 
strcpy(party[i].weap[0].wp_pc, "P"); 
strcpy(party[i].weap[0].wp_sc, "sc"); 
strcpy(party[i].weap[0].wp_sm, ""); 
strcpy(party[i].weap[1].wp_dsc, "Claw"); 
strcpy(party[i].weap[1].wp_tbl, "TC"); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 70; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 5; 
party[i].weap[1].wp_fm = 2; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, "S"); 
strcpy(party[i].weap[1].wp_sc, "pb"); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Missile"); 
strcpy(party[i].weap[3].wp_tbl, ""); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 0; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 0; 
party[i].weap[3].wp_fm = 0; 
party[i].weap[3].wp_br = 0; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, ""); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, ""); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 0; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 0; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, ""); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

strcpy(party[++i].Name, "Wight, Lesser"); 
party[i].Level = 0; 
party[i].HitsMax = 66; 
party[i].HitsCur = 66; 
party[i].NoAttks = 1; 
party[i].Bleed = 0; 
party[i].Stun = 0; 
party[i].ActPenalty = 0; 
party[i].Parry = 0; 
party[i].NoParry = 0; 
party[i].Inactive = 0; 
party[i].Death = 0; 
party[i].DBBase = 0; 
party[i].SpellBase = 0; 
party[i].DBShield = 0; 
party[i].SpellDirAttacks = 0; 
party[i].MMBase = 0; 
party[i].AGQU = 0; 
party[i].Armor = 0; 
party[i].CON = 90; 
party[i].Size = 1; 
party[i].DBLeg = 0; 
party[i].DBArm = 0; 
party[i].DBHelm = 0; 
party[i].IgnoreAtk = 0; 
party[i].CritAdj = 0; 
party[i].RRPoison = 0; 
party[i].RRChannel = 0; 
party[i].RRMentalism = 0; 
party[i].RREssence = 0; 
party[i].RRDisease = 0; 
party[i].Realm = 0; 
party[i].OBCur = 0; 
party[i].OBAdd = 0; 
party[i].DBSpecial = 0; 
party[i].MaMCur = 0; 
party[i].NoDefd = 0; 
party[i].perc = 0; 
party[i].track = 0; 
party[i].u_item = 0; 
party[i].r_rune = 0; 
party[i].p_lock = 0; 
party[i].d_trap = 0; 
party[i].influ = 0; 
party[i].stalk = 0; 
party[i].xp = 0; 
party[i].NoActions = 0; 
party[i].CurAction = 0; 
party[i].DoingOppAction = 0; 
party[i].SpellCharge = 0; 
party[i].MissileLoad = 0; 
party[i].CurWeapon = 0; 
party[i].DelayAttk = 0; 
party[i].AttackCount = 0; 
party[i].ActionCount = 0; 
party[i].Parry = 0; 
strcpy(party[i].weap[0].wp_dsc, "Melee"); 
strcpy(party[i].weap[0].wp_tbl, ""); 
party[i].weap[0].wp_sel = 0; 
party[i].weap[0].wp_ob = 0; 
party[i].weap[0].wp_ca = 0; 
strcpy(party[i].weap[0].wp_sz, ""); 
party[i].weap[0].wp_ma = 0; 
party[i].weap[0].wp_fm = 0; 
party[i].weap[0].wp_br = 0; 
party[i].weap[0].wp_bf = 0; 
party[i].weap[0].wp_str = 0; 
strcpy(party[i].weap[0].wp_pc, ""); 
strcpy(party[i].weap[0].wp_sc, ""); 
strcpy(party[i].weap[0].wp_sm, ""); 
strcpy(party[i].weap[1].wp_dsc, "Melee"); 
strcpy(party[i].weap[1].wp_tbl, ""); 
party[i].weap[1].wp_sel = 0; 
party[i].weap[1].wp_ob = 0; 
party[i].weap[1].wp_ca = 0; 
strcpy(party[i].weap[1].wp_sz, ""); 
party[i].weap[1].wp_ma = 0; 
party[i].weap[1].wp_fm = 0; 
party[i].weap[1].wp_br = 0; 
party[i].weap[1].wp_bf = 0; 
party[i].weap[1].wp_str = 0; 
strcpy(party[i].weap[1].wp_pc, ""); 
strcpy(party[i].weap[1].wp_sc, ""); 
strcpy(party[i].weap[1].wp_sm, ""); 
strcpy(party[i].weap[2].wp_dsc, "Melee"); 
strcpy(party[i].weap[2].wp_tbl, ""); 
party[i].weap[2].wp_sel = 0; 
party[i].weap[2].wp_ob = 0; 
party[i].weap[2].wp_ca = 0; 
strcpy(party[i].weap[2].wp_sz, ""); 
party[i].weap[2].wp_ma = 0; 
party[i].weap[2].wp_fm = 0; 
party[i].weap[2].wp_br = 0; 
party[i].weap[2].wp_bf = 0; 
party[i].weap[2].wp_str = 0; 
strcpy(party[i].weap[2].wp_pc, ""); 
strcpy(party[i].weap[2].wp_sc, ""); 
strcpy(party[i].weap[2].wp_sm, ""); 
strcpy(party[i].weap[3].wp_dsc, "Missile"); 
strcpy(party[i].weap[3].wp_tbl, ""); 
party[i].weap[3].wp_sel = 0; 
party[i].weap[3].wp_ob = 0; 
party[i].weap[3].wp_ca = 0; 
strcpy(party[i].weap[3].wp_sz, ""); 
party[i].weap[3].wp_ma = 0; 
party[i].weap[3].wp_fm = 0; 
party[i].weap[3].wp_br = 0; 
party[i].weap[3].wp_bf = 0; 
party[i].weap[3].wp_str = 0; 
strcpy(party[i].weap[3].wp_pc, ""); 
strcpy(party[i].weap[3].wp_sc, ""); 
strcpy(party[i].weap[3].wp_sm, ""); 
strcpy(party[i].weap[4].wp_dsc, "Thrown"); 
strcpy(party[i].weap[4].wp_tbl, ""); 
party[i].weap[4].wp_sel = 0; 
party[i].weap[4].wp_ob = 0; 
party[i].weap[4].wp_ca = 0; 
strcpy(party[i].weap[4].wp_sz, ""); 
party[i].weap[4].wp_ma = 0; 
party[i].weap[4].wp_fm = 0; 
party[i].weap[4].wp_br = 0; 
party[i].weap[4].wp_bf = 0; 
party[i].weap[4].wp_str = 0; 
strcpy(party[i].weap[4].wp_pc, ""); 
strcpy(party[i].weap[4].wp_sc, ""); 
strcpy(party[i].weap[4].wp_sm, ""); 
strcpy(party[i].weap[5].wp_dsc, ""); 
strcpy(party[i].weap[5].wp_tbl, ""); 
party[i].weap[5].wp_sel = 0; 
party[i].weap[5].wp_ob = 0; 
party[i].weap[5].wp_ca = 0; 
strcpy(party[i].weap[5].wp_sz, ""); 
party[i].weap[5].wp_ma = 0; 
party[i].weap[5].wp_fm = 0; 
party[i].weap[5].wp_br = 0; 
party[i].weap[5].wp_bf = 0; 
party[i].weap[5].wp_str = 0; 
strcpy(party[i].weap[5].wp_pc, ""); 
strcpy(party[i].weap[5].wp_sc, ""); 
strcpy(party[i].weap[5].wp_sm, ""); 

  if ((file = open("tab_xm.dat", O_CREAT | O_RDWR | O_TRUNC| O_BINARY)) == -1)
  {
     printf("\nUnable to OPEN tab_xm.dat\n");
     exit(0);
  }
  write(file, &party[0].Name[0], sizeof(players)*31);
  close(file);
}
